CREATE SEQUENCE SEQ_COLETA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_COLETA (
    ID_COLETA                 NUMBER(19)      NOT NULL,
    ID_PONTO_COLETA           NUMBER(19)      NOT NULL,
    ID_RESIDUO                NUMBER(19)      NOT NULL,
    DT_AGENDAMENTO            TIMESTAMP       NOT NULL,
    DT_COLETA                 TIMESTAMP,
    NR_QUANTIDADE_COLETADA    NUMBER(12, 2),
    ST_COLETA                 VARCHAR2(20)    NOT NULL,
    DS_OBSERVACAO             VARCHAR2(250),
    DT_CRIACAO                TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO            TIMESTAMP,

    CONSTRAINT PK_COLETA PRIMARY KEY (ID_COLETA),
    CONSTRAINT CK_COLETA_QTD CHECK (NR_QUANTIDADE_COLETADA IS NULL OR NR_QUANTIDADE_COLETADA >= 0),
    CONSTRAINT CK_COLETA_STATUS CHECK (ST_COLETA IN ('AGENDADA', 'EM_ANDAMENTO', 'REALIZADA', 'CANCELADA'))
);

CREATE INDEX IDX_COLETA_PONTO_COLETA
    ON T_COLETA (ID_PONTO_COLETA);

CREATE INDEX IDX_COLETA_RESIDUO
    ON T_COLETA (ID_RESIDUO);

CREATE INDEX IDX_COLETA_STATUS
    ON T_COLETA (ST_COLETA);
