CREATE SEQUENCE SEQ_PONTO_COLETA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_PONTO_COLETA (
    ID_PONTO_COLETA           NUMBER(19)      NOT NULL,
    NM_PONTO_COLETA           VARCHAR2(120)   NOT NULL,
    DS_ENDERECO               VARCHAR2(200)   NOT NULL,
    NM_CIDADE                 VARCHAR2(100)   NOT NULL,
    SG_ESTADO                 CHAR(2)         NOT NULL,
    NR_CEP                    VARCHAR2(10)    NOT NULL,
    NR_LATITUDE               NUMBER(10, 6),
    NR_LONGITUDE              NUMBER(10, 6),
    NR_CAPACIDADE_MAXIMA      NUMBER(12, 2)   NOT NULL,
    NR_CAPACIDADE_ATUAL       NUMBER(12, 2)   NOT NULL,
    DS_TIPO_RESIDUO_ACEITO    VARCHAR2(80)    NOT NULL,
    ST_PONTO_COLETA           VARCHAR2(20)    NOT NULL,
    DT_CRIACAO                TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO            TIMESTAMP,

    CONSTRAINT PK_PONTO_COLETA PRIMARY KEY (ID_PONTO_COLETA),
    CONSTRAINT CK_PONTO_COLETA_CAP_MAX CHECK (NR_CAPACIDADE_MAXIMA > 0),
    CONSTRAINT CK_PONTO_COLETA_CAP_ATUAL CHECK (NR_CAPACIDADE_ATUAL >= 0),
    CONSTRAINT CK_PONTO_COLETA_CAP_LIMITE CHECK (NR_CAPACIDADE_ATUAL <= NR_CAPACIDADE_MAXIMA),
    CONSTRAINT CK_PONTO_COLETA_STATUS CHECK (ST_PONTO_COLETA IN ('ATIVO', 'INATIVO', 'LOTADO'))
);

CREATE INDEX IDX_PONTO_COLETA_CIDADE
    ON T_PONTO_COLETA (NM_CIDADE);

CREATE INDEX IDX_PONTO_COLETA_STATUS
    ON T_PONTO_COLETA (ST_PONTO_COLETA);

CREATE INDEX IDX_PONTO_COLETA_TIPO_RESIDUO
    ON T_PONTO_COLETA (DS_TIPO_RESIDUO_ACEITO);
