CREATE SEQUENCE SEQ_RESIDUO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_RESIDUO (
    ID_RESIDUO             NUMBER(19)      NOT NULL,
    ID_PONTO_COLETA        NUMBER(19)      NOT NULL,
    NM_RESIDUO             VARCHAR2(100)   NOT NULL,
    DS_TIPO_RESIDUO        VARCHAR2(50)    NOT NULL,
    DS_RESIDUO             VARCHAR2(500),
    NR_QUANTIDADE          NUMBER(12, 2)   NOT NULL,
    DS_UNIDADE_MEDIDA      VARCHAR2(20)    DEFAULT 'KG' NOT NULL,
    ST_RESIDUO             VARCHAR2(20)    NOT NULL,
    DT_REGISTRO            TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DT_ATUALIZACAO         TIMESTAMP,

    CONSTRAINT PK_RESIDUO PRIMARY KEY (ID_RESIDUO),
    CONSTRAINT CK_RESIDUO_QUANTIDADE CHECK (NR_QUANTIDADE >= 0),
    CONSTRAINT CK_RESIDUO_STATUS CHECK (ST_RESIDUO IN ('ATIVO', 'INATIVO'))
);

CREATE INDEX IDX_RESIDUO_PONTO_COLETA
    ON T_RESIDUO (ID_PONTO_COLETA);

CREATE INDEX IDX_RESIDUO_TIPO
    ON T_RESIDUO (DS_TIPO_RESIDUO);

CREATE INDEX IDX_RESIDUO_STATUS
    ON T_RESIDUO (ST_RESIDUO);
